/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/gbf/drop/': RouteRecordInfo<'/gbf/drop/', '/gbf/drop', Record<never, never>, Record<never, never>>,
    '/gbf/gw/': RouteRecordInfo<'/gbf/gw/', '/gbf/gw', Record<never, never>, Record<never, never>>,
    '/gbf/note/': RouteRecordInfo<'/gbf/note/', '/gbf/note', Record<never, never>, Record<never, never>>,
    '/gbf/npc/': RouteRecordInfo<'/gbf/npc/', '/gbf/npc', Record<never, never>, Record<never, never>>,
    '/gbf/shenxian/': RouteRecordInfo<'/gbf/shenxian/', '/gbf/shenxian', Record<never, never>, Record<never, never>>,
    '/gbf/support/': RouteRecordInfo<'/gbf/support/', '/gbf/support', Record<never, never>, Record<never, never>>,
    '/other/playground': RouteRecordInfo<'/other/playground', '/other/playground', Record<never, never>, Record<never, never>>,
    '/other/slide': RouteRecordInfo<'/other/slide', '/other/slide', Record<never, never>, Record<never, never>>,
    '/other/trip': RouteRecordInfo<'/other/trip', '/other/trip', Record<never, never>, Record<never, never>>,
    '/raft/dishes/': RouteRecordInfo<'/raft/dishes/', '/raft/dishes', Record<never, never>, Record<never, never>>,
  }
}
